### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by shadrak98** [habiburrahman-mu/IOT-Based-Patient-Health-Monitoring-System-with-Blood-Group-Detection-Using-Image-Processing#1]
Can you be more specific about which sensors you used?

**Comment by habiburrahman-mu** [comment]
please consider this file:
https://github.com/habiburrahman-mu/IOT-Based-Patient-Health-Monitoring-System-with-Blood-Group-Detection-Using-Image-Processing/blob/master/Report%20-%20Copy.pdf
